### ISSUE TITLE
Change class

### ISSUE THREAD

**Issue by dimi-schepers** [SEMICeu/Core-Person-Vocabulary#10]
This issue can serve as the discussion forum to understand the need and use cases for the Change class and to further develop it. As taken from [the Core Vocabulary specification](https://joinup.ec.europa.eu/sites/default/files/distribution/2013-10/Core_Vocabularies-Business_Location_Person-Specification-v1.00_0.pdf):

_Any record can only be seen as a snapshot of the data available to the publisher at a particular point in time. This is true for data related to all areas, not just people, places and businesses. The Change class is envisaged as one that captures any change in a data point. This might be a change in address, a change of name or any other update. It is likely that such a record would make it clear what data element was changed as well as when, why and by whom. This area - versioning and provenance - is a complex one that the working group hopes will be tackled by a subsequent activity as a matter of high priority._

_The change relationship links a Class to a record of change in a data field associated with the Class. For example, a change of name or a person's their death. It is assumed that an inverse relationship will also be defined._

**Comment by dimi-schepers** [comment]
During the Core Vocs webinar dd. 2021-04-23, it was agreed that capturing changes over time are important, yet out-of-scope for the Core Vocabulary. Nevertheless, the editorial team will look into the creation of a Core Change Vocabulary, which could be useful for any registry.

**Comment by GeertThijs** [comment]
Such a vocabulary could be based on the famous book about modeling time by Snodgrass (2000). He distinguishes between 3 types of temporal elements:

- temporal datatypes
- types of time
- temporal statements

With the following subtypes:

- temporal datatypes: Moment, Interval, Period
- types of time: user-defined, validTime (= time in real-world), transactionalTime (=database time)
- temporal statements: currentVersion, successiveVersions, Versions

Several of these terms are already covered by [ISO 19108 Temporal Schema](https://www.iso.org/standard/26013.html) and are ready for reuse.

**Comment by EmidioStani** [comment]
During the webinar of 02/12/2021 it was agreed to keep timing part outside the scope of Core Vocabularies, however new use cases can be created in:  https://github.com/SEMICeu/Core-Person-Vocabulary/issues/new/choose
