### ISSUE TITLE
CountryOfBirth and PlaceOfBirth properties

### ISSUE THREAD

**Issue by giorgialodi** [SEMICeu/Core-Person-Vocabulary#12]
It is difficult to understand the difference between these two properties.

In general a country is also a place (at least looking at some foundational ontologies it seems so). I do not see the point to have two distinct properties or at least, if you want to quickly query the data with questions such as "which is the country of birth of person XXX", then I would say that countryOfBirth can be maintained but it can be viewed  probably as a sub property of a generic property placeOfBirth.

**Comment by dimi-schepers** [comment]
During the Core Vocs webinar dd. 2021-04-23, it was decided to keep both properties. An example will be added to the specification to highlight the added value of having both properties, e.g. a city whose name exists in multiple countries.

**Comment by giorgialodi** [comment]
@dimi-schepers I am not sure to have understood the example you provide here. It seems to me that it can be dealt with just one property, place of birth for instance (if a city exists in multiple countries, if you use nut you can derive the country from there). A country is a place, that's the reason of my comment above. Therefore, if you wish to maintain both properties you need to provide examples when to you placeOfBirth and when to use instead countryOfBirth.  Probably place of birth when you specify the city and country of birth when you specify the country?

**Comment by dimi-schepers** [comment]
@giorgialodi If I understood correctly, the intended usage is indeed to use placeOfBirth for the city. But the benefit of having two properties arises mainly when you use the geographicName property and not the URI. E.g. there is no issue when you do
```
ex:1 a cv:Person ;
  placeOfBirth [
    a dct:Location ;
    geographicIdentitifier <https://sws.geonames.org/2988507/> 
  ] .
```
but there can be disambiguity when you have
```
ex:2 a cv:Person ;
  placeOfBirth [
    a dct:Location ;
    geographicName "Paris"@en  
  ] .
```
as there exist a city of Paris in France, but also in the United States. So to clarify, it should then become
```
ex:2 a cv:Person ;
  placeOfBirth [
    a dct:Location ;
    geographicName "Paris"@en  
  ] ;
  countryOfBirth [
    a dct:Location ;
    geographicName "France"@en  
  ]
```

**Comment by EmidioStani** [comment]
The definitions of country and place of birth have been updated together with other entities: https://github.com/SEMICeu/Core-Person-Vocabulary/blob/master/releases/2.00/Changelog_definitions.md
