### ISSUE TITLE
Concept definition for gender

### ISSUE THREAD

**Issue by giorgialodi** [SEMICeu/Core-Person-Vocabulary#13]
The definition of Concept is ok but I would write why we use it here. Because we want to specify the gender as a concept of a specific controlled vocabulary.

In Italy we used the world "gender" at the beginning but our National Institute of Statistics asked us to change it in "sex". They have two different meanings and we need to pay attention here to what we want to represent (biological elements or the sexuality perceived by the society, to simplify?)

**Comment by aidig** [comment]
There is a risk here of confusing sex (biology) and gender (identity). For instance ‘intersex’ refers to a sex. Unfortunately, the usage note for gender suggests the the property can be used for both sex and gender, while the definition itself adds no meaning besides the term. By using one property to mean two distinct things interoperability is lost. In this case specifically it introduces a risk of errors, where sex may be read as gender, something that can be very hurtful to people for whom the two are not the same. Therefore the property should be specified to only cover gender. If there is a need to know a person’s biological sex a separate property would be needed, though it’s hard to see a legimate use for this outside of the health care sector, so it may not be appropriate to include it in a core vocabulary, which may suggest to some implementers that it should be included. 
And, yes, the options for gender should - at a minimum - include ‘diverse’. 

Comment provided by:
https://github.com/mayaborges
https://github.com/aidig

**Comment by aidig** [comment]
There are indeed many aspects to consider here, legal, social, biological. But what is probably mainly registered in the basic person registries of the MS is the legal aspect, which of course is dependent on the legislation of that particular country.

Thought SnomedCT might shed some light on the biological aspects of the matter, but noted that the Bioportal also has information about a so-called Gender, Sex, and Sexual Orientation Ontology (GSSO), which sounds like it might be relevant although I have not looked further into the ontology. https://bioportal.bioontology.org/ontologies/GSSO?

**Comment by giorgialodi** [comment]
I do not see the confusion here because we all raised the point of distinguishing between sex and gender, recognizing that  they are different terms with different semantics. In the last meeting some proposed to include both and I think it can be wise choice: a person can be indeed described according to these two elements.  In my country there is a current long discussion about gender, so I would really consider both properties so that to have a wider coverage of possibilities.

**Comment by dimi-schepers** [comment]
As mentioned above, during the Core Vocs webinar dd. 2021-04-23, the participants agreed to differentiate sex and gender and to include both within the Core Vocabulary. A preference was also stated to recommend codelists that have a legal basis.

**Comment by EmidioStani** [comment]
The definition and the usage note of gender has been updated here together with other entities: https://github.com/SEMICeu/Core-Person-Vocabulary/blob/master/releases/2.00/Changelog_definitions.md
