### ISSUE TITLE
Clarification on the Jurisdiction class

### ISSUE THREAD

**Issue by giorgialodi** [SEMICeu/Core-Person-Vocabulary#15]
Jurisdiction should be better specified with examples IMHO because it was not very clear in the past and it is still not clear now.
I mean, is it a Location? If so, why do not we use Location of CLV then? Which are the individuals of the class Jurisdiction?

Because if I say that Giorgia has citizenship I would say Italian not Italy. And also residency. I typically say in all the forms that I am resident in "street XXX, number YYY, Rome, Italy" so I say that I am resident in a specific address not simply in a country. 

So clarifying the concept of Jurisdiction is important.
BTW: the residency may definitely change over time, especially if you think to specify the residency in an address. However, this aspect is not modelled.

**Comment by GeertThijs** [comment]
The original ISA Core Person vocabulary used http://purl.org/dc/terms/Jurisdiction. This is defined as "The extent or range of judicial, law enforcement, or other authority.". Where extent can be interpreted geographically and range as reach. So in fact this covers Residency as well as Citizenship. The first gives you the right to take Residence somewhere, the latter to exercise certain rights like the right to vote. Jurisdiction materializes usually as State (similar to Country). ISA has a term for residency as well as one for citizenship, both are associations between Person and Jurisdiction.. If residency where a class, then its subtypes would be PermanentResident, TemporaryResident, NoResident. And citizenship as a class could be subtyped as Citizen and Foreigner. These subclasses actually exist in Belgium and I think they can be applied universally. See [OSLO-project](https://overheid.vlaanderen.be/oslo-wat-is-oslo) for more info and more in particular its [Person extensions](https://data.vlaanderen.be/doc/applicatieprofiel/persoon-basis) on ISA.

**Comment by EmidioStani** [comment]
The jurisdiction definition has been updated together with the rest of classes/entities:  https://github.com/SEMICeu/Core-Person-Vocabulary/blob/master/releases/2.00/Changelog_definitions.md
