### ISSUE TITLE
BirthDate as W3C Date not sufficient, more and more incomplete birth dates do exist

### ISSUE THREAD

**Issue by SebastianSK** [SEMICeu/Core-Person-Vocabulary#17]
The dateOfBirth and the dateOfDeath should be able to handle **incomplete** dates for the following reasons:

In Germany several non Germans do exist or arrived in latest times that do not know the exact date of Birth. Often - having lost all passport information - persons can state a year but not a month and a day. 
Same incomplete information exists for other dates like "the date when the European Union was entered"

The need for a complex data type is given as you can not state 1st of January (1980-01-01) in the case that you want to express that all you know is the year (1980).

In Germany we use constructs like (Ausländerzentralregister) 
`teilbekanntesDatum` (partly known date) 
or `teilbekanntesDatumMitUnbekannt`

The suggestion is to use in addition to Date a complex date type allowing to express the uncertainty about the month and / or day.

![image](https://user-images.githubusercontent.com/3493618/115831159-80f6f680-a411-11eb-9e20-88ea7433ea88.png)

![image](https://user-images.githubusercontent.com/3493618/115831691-3b86f900-a412-11eb-83e3-0ba3a5d76edc.png)

**Comment by makxdekkers** [comment]
There is an extension of ISO 8601 that allows for uncertain dates: EDTF https://www.loc.gov/standards/datetime/

**Comment by mayaborges** [comment]
There may even be times where the registered year is a 'best guess', e.g. for children that have been seperated from their families. 

The Danish Civil Registration System uses a 'dateOfBirthUncertaintyMarking' to allow for marking that the date of birth cannot be confirmed.

**Comment by dimi-schepers** [comment]
During the Core Vocs webinar dd. 2021-04-23, participants agreed to use xsd:date as the data type for the date of birth/death, together with a clear recommendation in the usage note of the property on how to handle specific cases, such as when part or the entire date is unknown as mentioned above. 

Examples of recommendations include using EDTF, ISO8601 which can deal with truncated dates and ISO 8601-2:2019 which has a notion of "uncertain" date. Several participants were in favour of having both `xsd:date` AND a composed data type which could be a text with some standard syntax for this.

**Comment by EmidioStani** [comment]
During the webinar of 02/12/2021 it was agreed to create a datatype Date as union of xs:date, xs:gYearMonth and xs:gYear

**Comment by EmidioStani** [comment]
The new datatype date has been added in the Consolidated Diagram (EAP version): https://github.com/SEMICeu/Core-Person-Vocabulary/blob/master/releases/2.00/ISA_Core_Vocabularies_2.00.EAP
