### ISSUE TITLE
Inconsistency between data types in XSD (text type) and specification (code)

### ISSUE THREAD

**Issue by SebastianSK** [SEMICeu/Core-Person-Vocabulary#18]
The specification says that the CorePerson.Gender is a Code and that the Publications Office Gender codelist has to be used.
The XSD file in V1.0 (did not find yet the xsds for 2.2) uses a data type "text" for gender. (same for Core Location AdminUnitL1 ).

![image](https://user-images.githubusercontent.com/3493618/115832665-6de52600-a413-11eb-9c2e-624a4fe68e96.png)

The recommendation is to use the data type URI or an own data type for codelists but not text.

**Comment by EmidioStani** [comment]
As it relates to version 1.0 not supported this issue can be closed, however this consideration of XSD should be taken in mind
