### ISSUE TITLE
Add a way to express that a givenName or a familyName does not exist

### ISSUE THREAD

**Issue by SebastianSK** [SEMICeu/Core-Person-Vocabulary#19]
As stated already in the SDG exercise https://github.com/SEMICeu/SDG-sandbox/issues/134 
several people do exists that do not have one of the both name components. (givenName or FamilyName)

eIDAS made both name components mandatory but this is another legal / organisational interoperability issue.

Currently Core Person to my understanding does not have cardinalities that do oblige all name components to exist.
But also Core Person has no ways of telling that something was not obmitted because it is not present (see also incomplete dates as a similar topic https://github.com/SEMICeu/Core-Person-Vocabulary/issues/17  ) 

In Germany we can tell whether a name component was obmitted intentionally - reflecting the fact that it does not exist.
The element is called "zu Recht nicht vorhanden" and greatly helps increasing data quality as all un-intentionally missing name components can be rejected in data exchange thanks to this "`NameWithAbsentOptionType.`"

The suggestion is to add to core person an optional boolean element that tells that the Firstname or Familyname does legally not exist and was not just obmitted by fault.

**Comment by EmidioStani** [comment]
Indeed, Core Vocabularies do not say anything about cardinalities.
Any of the properties may be used zero, one or multiple times. Any restrictions to their use can be defined in an application profile for a specific use context, thus adding such property could be possible in an application profile.
