### ISSUE TITLE
Terminology and definitions in the core vocabularies 

### ISSUE THREAD

**Issue by aidig** [SEMICeu/Core-Person-Vocabulary#21]
see https://github.com/SEMICeu/CPOV/issues/12

**Comment by barthelemyf** [comment]
The editors have:
* created (syntax) rules for writing definitions of the Core Vocabularies ([Github link](https://github.com/SEMICeu/CPOV/blob/master/generic/Principles%20for%20creating%20good%20definitions_v1.00.pdf)) – Feedback is welcome!
* reviewed the existing definitions w.r.t. to these rules and adapted them where needed – the supporting spreadsheet will be shared.

**Comment by EmidioStani** [comment]
Updated definitions have been published on: https://github.com/SEMICeu/Core-Person-Vocabulary/blob/master/releases/2.00/Changelog_definitions.md
