### ISSUE TITLE
Addition of Parents' names (Parent 1 and Parent 2)

### ISSUE THREAD

**Issue by jerouris** [SEMICeu/Core-Person-Vocabulary#22]

**Comment by EmidioStani** [comment]
The working group looked at the Public Document regulation without any finding:
https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32016R1191&from=EN#d1e41-20-1

Please provide a better use case with: https://github.com/SEMICeu/Core-Person-Vocabulary/issues/new/choose

In any case, Core Vocabularies do not put any restrictions and implementers can add more properties/relations if needed
