### ISSUE TITLE
Definition of date of birth/death

### ISSUE THREAD

**Issue by dimi-schepers** [SEMICeu/Core-Person-Vocabulary#28]
During the Core Vocs webinar dd. 2021-04-23, the definition of date of birth/death was questioned. The "day" in the definition seems reductive. The example was given that being born on the 8th does not represent the dateOfBirth. And replacing “day” by “date” would lead to a circular definition, making it tautologic. A reference was made to ISO 11179 regarding how to address definitions of data elements.

**Comment by EmidioStani** [comment]
New definitions about birth/death data have been published in version 2:

https://github.com/SEMICeu/Core-Person-Vocabulary/blame/master/releases/2.00/Changelog_definitions.md#L104
