### ISSUE TITLE
Identifier scheme

### ISSUE THREAD

**Issue by dimi-schepers** [SEMICeu/Core-Person-Vocabulary#29]
During the Core Vocs webinar dd. 2021-04-23, a proposition was made to add the scheme to the Identifier class. A suggestion was made to use `dct:conformsTo` for this. It was mentioned that in the eProcurement ontology a schemeName and schemeURI are defined.

**Comment by EmidioStani** [comment]
The scheme name has been added in the Identifier class: https://semiceu.github.io/Core-Person-Vocabulary/releases/2.00/#Identifier
