### ISSUE TITLE
Align Core Person with Public Documents Schemas

### ISSUE THREAD

**Issue by SusanneWigard** [SEMICeu/Core-Person-Vocabulary#3]
[Public Documents and Core Vocabularies.xlsx](https://github.com/SEMICeu/Core-Person-Vocabulary/files/3345615/Public.Documents.and.Core.Vocabularies.xlsx)
Since the Public Documents Regulation establishes the names for all attributes of a person as given e.g. in the Birth and Death certificates and this has been agree by all Member States, the ISA Core Person would benefit from using the same names (e.g. Surname instead of FamilyName, ForeName instead of GivenName, or distinguishing between Domicile and Residence instead of Adress).
Also, these certificate distinguish between Surnames before and after certain life events (e.g. marriage, registered partnership), which have in the Public Documents schemas been modelled by adding to each certificate elements "SurnameBefore" and "SurnameAfter ". It could be considered to add these also to the Core Person Vocabulary. 
The attached Excel lists all potential improvements.

**Comment by EmidioStani** [comment]
During the webinar of 02/12/2021 it was agreed to add the relation Domicile between Person and Address, indicating the permanent address of a Person.

**Comment by EmidioStani** [comment]
The new relation results in the consolidated diagram: https://github.com/SEMICeu/Core-Person-Vocabulary/tree/master/releases/2.00
