### ISSUE TITLE
Remove dependence on schema.org

### ISSUE THREAD

**Issue by dimi-schepers** [SEMICeu/Core-Person-Vocabulary#30]
During the Core Vocs webinar dd. 2021-04-23, it was agreed to maximally remove the dependence on schema.org, as was similarly decided for the other Core Vocabularies, e.g. CPOV.

**Comment by NatasaSofou** [comment]
Currently there are three properties from schema.org:  gender, dateOfBirth and dateOfDeath. Which  are the new URIs for these properties?I In order to reuse the Person Vovabulary we need to know this information.

**Comment by EmidioStani** [comment]
Schema.org has been removed and replaced by cv namespace
