### ISSUE TITLE
Role / Participation

### ISSUE THREAD

**Issue by dimi-schepers** [SEMICeu/Core-Person-Vocabulary#31]
During the Core Vocs webinar dd. 2021-04-23, some voices were in favour of modelling how an Agent or Person may have different roles/participations. It is however not clear yet whether this should (1) be part of one of the existing Core Vocabularies, (2) have its own vocabulary, (3) be part of an upper-level ontology.

Both CPSV-AP and the eProcurement Ontology have classes that can serve as inspiration.

**Comment by EmidioStani** [comment]
CPSV-AP uses Participation class under Core Vocabularies, no change is required
