### ISSUE TITLE
Secondary/temporary address

### ISSUE THREAD

**Issue by dimi-schepers** [SEMICeu/Core-Person-Vocabulary#32]
During the Core Vocs webinar dd. 2021-04-23, a suggestion was made to include a secondary or temporary address.

**Comment by EmidioStani** [comment]
During the webinar of 02/12/2021 it was agreed to add the relation Domicile between Person and Address, indicating the permanent address of a Person.

Additional address could be part of future work of the working group

**Comment by EmidioStani** [comment]
This issue has been implemented in the consolidated diagram: https://github.com/SEMICeu/Core-Person-Vocabulary/blob/master/releases/2.00/ISA_Core_Vocabularies_2.00.jpg
