### ISSUE TITLE
Extensions

### ISSUE THREAD

**Issue by GeertThijs** [SEMICeu/Core-Person-Vocabulary#35]
I am not sure if extending the original Core Person Vacabulary is in scope here, but if it was I would add the following concepts:

- RegisteredPerson (for Persons that are officially registered eg for social security reasons or official identification, subclass of Person).
- Residency as a class (which then can be subclassed with concepts like PermanentResident, TemporaryResident, NoResident, Could be an association class on the residency association between Person and Jurisdiction, has residence as attribute with Residence as class and Domicile as subclass).
- Citizenship as a class (with subclasses like Citizen and Foreigner).
- PersonalEvent (for things like Birth, Death, Marriage etc).
- Nationality.
- CivicState.
- Household.
- PersonalRelation (with subclasses like Lineage, Marriage, Custody etc).

We included all this in our own semantic [OSLO-standard](https://overheid.vlaanderen.be/oslo-wat-is-oslo) for [Person info](https://data.vlaanderen.be/doc/applicatieprofiel/persoon-basis).

**Comment by EmidioStani** [comment]
During the webinar of 02/12/2021 it was agreed to add the relation Domicile between Person and Address, indicating the permanent address of a Person.

**Comment by EmidioStani** [comment]
This issue has been applied in the consolidated diagram: https://github.com/SEMICeu/Core-Person-Vocabulary/blob/master/releases/2.00/ISA_Core_Vocabularies_2.00.jpg
