### ISSUE TITLE
Proposal to create ContactInfo

### ISSUE THREAD

**Issue by EmidioStani** [SEMICeu/Core-Person-Vocabulary#36]
Following discussion on https://github.com/SEMICeu/CPOV/issues/16 and https://github.com/SEMICeu/Core-Person-Vocabulary/issues/5 a proposal would be creating the class ContactInfo with the following properties:

- name 
- telephone
- email 
- address 
- type 

we can start discuss on the minimum number of properties, later to see the namespaces

**Comment by williamverbeeck** [comment]
As there are no additional requirements the proposal is to reuse the [ContactPoint class](https://semiceu.github.io/CPOV/releases/2.1.0/#Contact%20Point) and the [contactPoint relation](https://semiceu.github.io/CPOV/releases/2.1.0/#Public%20Organisation%3Acontact%20point) with a Person class.

**Comment by EmidioStani** [comment]
This issue is solved in release [2.1.0](https://semiceu.github.io/Core-Person-Vocabulary/releases/2.1.0/)
