### ISSUE TITLE
Validate JSON-LD Context for errors before publishing

### ISSUE THREAD

**Issue by amiika** [SEMICeu/Core-Person-Vocabulary#41]
### Use case name

JSON-LD Context validation and examples

### Use case creator

Miika Alonen

### Stakeholders

Everyone using JSON-LD and SEMIC vocabularies

### Problem statement

Current release of the JSON-LD Context is invalid. Missing [type on a property](https://github.com/SEMICeu/Core-Person-Vocabulary/blob/master/releases/2.00/context/core_person.jsonld#L14). There is also multiple occurrences of @id where it should be string. Some property names (like "Address.administrativeUnitLevel1 (country)" also seems very odd.

Publishing non-functioning vocabulary (even if draft) is a big credibility problem. 

### Requirements

Create example JSON-LD documents and validation process for the JSON-LD context.

**Comment by EmidioStani** [comment]
Thanks for reporting this, the JSON-LD context is automatically generated from the UML class diagram, sure that quality has to be checked.

I have a valid RDF:
{  
  "@id" : "http://mytest.com",
  "@type": "http://www.w3.org/ns/locn#Address",
  "@context": "https://semiceu.github.io/Core-Person-Vocabulary/releases/2.00/context/core-person-ap.jsonld",
  "Address.administrativeUnitLevel1 (country)" : {
    "@value": "France",
    "@language": "fr"
  }
}

that works with EasyRDF and RDF Blue Mix
