### ISSUE TITLE
Revise Agent and potentially add contact details

### ISSUE THREAD

**Issue by SusanneWigard** [SEMICeu/Core-Person-Vocabulary#5]
The conceptual model (UML diagram) and the RDF representation of Core Vocabularies reference foaf:agent. The XML representation defines its own Agent with no reference to foaf and quite different properties. 

Both Person and Organisation (Business) have an address but no other contact details. From foaf: agent they would inherit a lot about social media but I don't see simple things like a telephone number. 

Reusing Core Vocabularies in the context of public administration (specifically: EFTI) would benefit from both Person and Organisation having contact details, so these should probably be in the superclass Agent.

**Comment by GeertThijs** [comment]
Agent in FOAF is defined as "An agent (eg. person, group, software or physical artifact).". And it is equivalent to DCTERMS Agent which is defined as "A resource that acts or has the power to act.". So not every Agent is a Person or Organisation and thus has an Address or other ContactInfo, eg if the Agent is a SoftwareProgram. As such it is preferable to just add an attribute contactinfo with datatype Contactinfo to Person as well as to Organisation with the proper attributes like telephone, email, contactaddress, contactname etc (see schema.org:ContactPoint for inspiration).

**Comment by EmidioStani** [comment]
Discussion will continue on https://github.com/SEMICeu/Core-Person-Vocabulary/issues/36
