### ISSUE TITLE
Bach's first name is Johann with double "n"

### ISSUE THREAD

**Issue by dimi-schepers** [SEMICeu/Core-Person-Vocabulary#8]
In the definition of given name, Bach's name is misspelled: "Johan" instead of "Johann".

Credits to XHochschuleDE: https://github.com/SEMICeu/SDG-sandbox/issues/124

**Comment by EmidioStani** [comment]
This has been fixed in the HTML specification: https://semiceu.github.io/Core-Person-Vocabulary/releases/2.00/
